### ISSUE TITLE
missing DB

### ISSUE THREAD

**Issue by developerfranso** [mmckendry/KD-Office-Management-Project#1]
The systm is good where is the sql file please

**Comment by mmckendry** [comment]
Hi there is no SQL file because the database was created separately and the system simply connected to it. At the moment i cant remember the database structure that was used as it was a long time ago that it was created. I'll work on it later this evening and post up the file when i recreate it. Thanks for bringing it to my attention.

**Comment by developerfranso** [comment]
ok thanks i will appreciate

**Comment by mmckendry** [comment]
Hey the SQL file is simple enough to recreate. I made it in PHPMyAdmin so i don't have the file itself. But you should just have to create a database (the system tries to connect to one called "login" in the 'config.php' ill add a comment shortly to where you can rename it to your own.) Then add a table 'users' with 8 columns called; UID, EMAIL, PASSWORD, FIRSTNAME, LASTNAME, PRIVILEGE, ACTIVATED, ACTIVATION_CODE. You will also NEED to know your way around PHPMailer found here: https://github.com/Synchro/PHPMailer as the system uses automatic emails. There is still redundant code that i will clean up that might still cause some problems. I hope to have it fixed up tomorrow.

**Comment by developerfranso** [comment]
ok thanks so muchh
